steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service', '.']
    env:
      - 'DOCKER_BUILDKIT=1'
    secretEnv: ['ENV_FILE']
    
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/env-file/versions/latest
      env: 'ENV_FILE'

images:
  - 'gcr.io/$PROJECT_ID/backend-service'